name: Deploy to Cloudzilla
on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_PREFIX: registry.cloudzilla.ai/lens-project-64a7d029/

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: downcase REPO
        run: |
          image="${GITHUB_REPOSITORY#*/}"
          echo "IMAGE_NAME=${image,,}" >>${GITHUB_ENV}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_PREFIX }}${{ env.IMAGE_NAME }}
          
      - name: Valiate existing .env file
        run: |
          # Path to your .env file
          ENV_FILE=".env"

          # Read the .env file line by line
          while IFS= read -r line || [ -n "$line" ]; do
              # Remove leading and trailing whitespace
              line="$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"

              # Skip empty lines
              if [ -z "$line" ]; then
                  continue
              fi

              # Skip comment lines starting with #
              if [[ "$line" == \#* ]]; then
                  continue
              fi

              # Check if the line matches KEY=VALUE format
              if ! [[ "$line" =~ ^[A-Za-z_][A-Za-z0-9_]*=.*$ ]]; then
                  echo "this file is not valid"
                  exit 1
              fi
          done < "$ENV_FILE"
